### ISSUE TITLE
Meaning of phoneme scores

### ISSUE THREAD

**Issue by LyWangPX** [YuanGongND/gopt#14]
For any utterance, is the 5 phoneme scores returned by the model representing the phoneme-level score of the whole utterance?
What should be the shape of the phoneme score? In my case, I always obtain 1-dim numeric result for each phoneme score.

So if it is true, why it is still considered a phoneme score instead of an utterance score since it is an average phone score of the utterance?

**Comment by YuanGongND** [comment]
Hi there, 

I think the 5 scores are different aspects (e.g., accuracy, completeness, ...) of *utterance-level* scores instead of phone-level scores. In addition, utterance-level score is not a simple average of phone-level scores, instead, an attention mechanism is applied. We only have 1 score (i.e., 1d float) for each phone. 

https://github.com/YuanGongND/gopt/blob/6d50553ce02941c4accde767818a369700a1007a/src/models/gopt.py#L211-L226

Does this answer your question?

-Yuan

**Comment by LyWangPX** [comment]
Thanks for your clarification!

**Comment by YuanGongND** [comment]
You are welcome. Btw, I think the [colab script](https://colab.research.google.com/github/YuanGongND/gopt/blob/master/colab/GOPT_GPU.ipynb) might be the easiest way to check the shape of tensors.
