### ISSUE TITLE
Where can I find L2 data used in PAII-A an PAII-B

### ISSUE THREAD

**Issue by franknoerror** [YuanGongND/gopt#3]
Nice Work and thank you for your code! 

I found that 1696 / 6591 hours of L2 data is used in training of the PAII-A / PAII-B. I'm impressed by the 1696 / 6591 number. I want to ask where I can find these data. Are they public?

**Comment by YuanGongND** [comment]
Hi there,

They are not public - so as is the PAII-A/B acoustic model. They are properties of PAII Inc. If interested, please consult the senior author from PAII. 

For this reason, we grey out the result of PAII-A/B in Table I and only compare GOPT with a public AM trained with Librispeech with existing methods. Also, the L2 data we used to train PAII-A/B is independent from SO762 as they are from totally different sources. 

Nevertheless, we do provide the GOP features extracted by PAII-A/B, so that you can 1) reproduce our result (one click by [the colab script](https://colab.research.google.com/github/YuanGongND/gopt/blob/master/colab/GOPT_GPU.ipynb)); and 2) develop and train your own scoring model with the provided PAII-A/B GOP features and make a fair comparison with our GOPT method. 

-Yuan

**Comment by franknoerror** [comment]
Ooh, got it! Thank you so much!
